version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/TodoApp.WebApi/Dockerfile #src\TodoApp.WebApi
    ports:
      - "5245:8080"
      - "7215:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=TodoDb;Username=myuser;Password=mypassword #Host=db;Database=todo_db;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: TodoDb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
